# frozen_string_literal: true
source "https://rubygems.org"

gem 'rake'

gem 'rack'
gem 'rack-test'
gem 'rack-cors', require: 'rack/cors'
gem 'roda'

gem 'halogen'

gem 'rom'
gem 'rom-repository'
gem 'rom-sql'
gem 'sqlite3'

gem 'dry-system'
gem 'inflecto'

group :development, :test do
  gem 'pry'
end

group :test do
  gem 'rspec'
  gem 'rspec-hal'
  gem 'cucumber'

  gem 'rom-factory'
end
