# frozen_string_literal: true
source "https://rubygems.org"

gem 'rake'

gem 'rack'
gem 'rack-test'
gem 'rack-cors', require: 'rack/cors'
gem 'roda'

gem 'halogen'

gem 'rom'
gem 'rom-repository'
gem 'rom-sql'
gem 'sqlite3'

gem 'dry-system'
gem 'inflecto'

group :development, :test do
  gem 'pry'
  gem 'byebug'
  gem 'pry-byebug'
end

group :test do
  gem 'rspec', '> 3', '< 4'
  gem 'rspec-hal'
  gem 'cucumber', '3.0.0.pre.1'

  gem 'rom-factory'
end
