steps:
  - command: docker-compose build && docker-compose run api ci/server_cukes.sh
    label: "Server Cukes"
  - command: docker-compose build && docker-compose run api ci/server_specs.sh
    label: "Server Specs"
